### PR TITLE
Meta keys should not match.

### PR DESCRIPTION
**Pull request by robdodson**
Addresses heuristic update in #167.

@alice PTAL when you have a chance 😸

### CODE REVIEW

**Comment by alice** [comment]
:+1: once we figure out what's up with the tests.

**Comment by robdodson** [comment]
@cdata 	I'd like to land this before releasing v5 since it's also a breaking change. I'll add it to my calendar to get this sorted tomorrow.

**Comment by karlhorky** [comment]
Is there any timeline on when v5 will be released?

Would like to upgrade to this whenever that drops, so that I don't need to [stay pinned to `4.0.1`](https://github.com/WICG/focus-visible/pull/118#issuecomment-486157073).

**Comment by robdodson** [comment]
I can try to roll it out tomorrow

**Pull request merged**
