### PR TITLE
Reduce bundle size by defining pointerMoveEvents array

### PR DESCRIPTION
**Pull request by wojtekmaj**
Instead of 18 almost identical lines, use pointerMoveEvents array to keep track of all listeners to add/remove in addInitialPointerMoveListeners and removeInitialPointerMoveListeners respectively.

### CODE REVIEW

**Comment by Justineo** [comment]
Have you compared the gzipped size of the bundle? “Almost identical” means you’ll have a very good compression ratio.

**Comment by yoavweiss** [comment]
@wojtekmaj - can you join the WICG to appease the IPR bots? Thanks! :)

**Comment by robdodson** [comment]
hm it seems like a bunch of tests are failing. Were they passing for you locally? I'm wondering if some part of our setup is busted.

**Comment by wojtekmaj** [comment]
Looks like the tests are failing because Array.forEach is not supported on IE.

**Pull request closed without merging**
